version: '3'
services:
  db:
    image: 'mysql:5.7'
    restart: always
    container_name: mysqllocal
    environment:
      MYSQL_ROOT_PASSWORD: 98LNaNmPjJbesmEI
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M;
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
